# Generated by Django 2.0.5 on 2019-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
