# Generated by Django 2.0.5 on 2019-04-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_bith',
            new_name='date_of_birth',
        ),
    ]
